version: "3"
services:
  jenkins:
    image: kkmadhpuriya/jenkins-with-docker:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=Krishna@1640
    networks:
      - proxy

networks:
  proxy:
    name: proxy-server_default
    external: true
